# Generated by Django 6.0.1 on 2026-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('usn', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('collage', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=64)),
                ('branch', models.CharField(max_length=64)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
